Topic logical operators
mhavrylova/learn-js pull request #15
Opened 2023-10-08 21:40 UTC by mhavrylova

2023-10-10 19:12 UTC, andrii-olefir-airslate commented on part1-java-script-fundamentals/chapter-3/logical-operators/logical-operators.html
> +        <br>Є трохи довший спосіб зробити те ж саме – вбудована функція <span class="code">Boolean</span>
Я зазвичай намагаюсь використовувати Boolean(99) тому-що на мою особисту думку це біль явне приведеня до буліан типу

2023-10-10 19:18 UTC, andrii-olefir-airslate commented on part1-java-script-fundamentals/chapter-3/logical-operators/tasks/task1.js
> +let age = prompt('enter your age', '');
1. використовуй const замість let якщо ми не плануємо змінювати зміну
2. зайвий пробіл після && 
3. 14 та 90 перенести до констант MIN_AGE та MAX_AGE та замінити 'your age is in diapason 14-90' на `your age is in diapason ${MIN_AGE}-${MAX_AGE}`

2023-10-10 19:21 UTC, andrii-olefir-airslate commented on part1-java-script-fundamentals/chapter-3/logical-operators/tasks/task2.js
> +let ageValidation2 = !(age2 >= 14 && age2 <= 90) ? 'your age is not in diapason 14-90' : 'your age is in diapason 14-90';
теж саме як і у першій задачі

!(age2 >= 14 && age2 <= 90) ? 'your age is not in diapason 14-90' : 'your age is in diapason 14-90'; так краще не робити просто поміняти місцями кейси після '?'
age2 >= 14 && age2 <= 90 ?  'your age is in diapason 14-90' : 'your age is not in diapason 14-90';

2023-10-10 19:26 UTC, andrii-olefir-airslate commented on part1-java-script-fundamentals/chapter-3/logical-operators/tasks/task3.js
> +function checkLogin() {
const vs let
"Who\'s there?\n" - зайва екранація \' томущо це знаходится у "" лапках 
\n нащо тут нова строка?
зновуж таке "Admin" такі речі кращє зберігати в константах

розумію що це може здаватись зайвим в домашніх задачах, але нам потрібно напрацьовувати одразу чисті рішеня, щоб в майбутньому вони робились автоматично

2023-10-10 19:28 UTC, andrii-olefir-airslate reviewed
залишив пару мінорних коментів по синтаксису

2023-10-10 19:29 UTC, andrii-olefir-airslate requested changes
залишив пару мінорних коментів

2023-10-12 20:13 UTC, mhavrylova commented on part1-java-script-fundamentals/chapter-3/logical-operators/tasks/task2.js
> +let ageValidation2 = !(age2 >= 14 && age2 <= 90) ? 'your age is not in diapason 14-90' : 'your age is in diapason 14-90';
щодо !(age2 >= 14 && age2 <= 90) - така була умова задачі: Створіть два варіанти: перший з оператором НЕ !, другий — без нього. 
Але меседж зрозуміла)

2023-10-12 20:15 UTC, mhavrylova commented on part1-java-script-fundamentals/chapter-3/logical-operators/tasks/task3.js
> +function checkLogin() {
ці екранації чомусь вебшторм самостійно повиставляв, як і ту зайву строку. Не можу розібратись нащо він так робить

2023-10-20 16:53 UTC, andrii-olefir-airslate approved these changes

2023-10-23 08:20 UTC, merged